import type { ItemType } from '@prisma/client'

export interface MaintenanceCategoryDef {
  value: string
  label: string
}

// Category *values* are persisted as free-form strings (see maintenance.schema.ts),
// not a DB enum — so this list can grow per item type without a migration. Existing
// records keep displaying fine even if their category isn't in the current list for
// that type (MaintenanceList falls back to a generic badge color for unknown values).
const MAINTENANCE_CATEGORIES: Record<ItemType, MaintenanceCategoryDef[]> = {
  VEHICLE: [
    { value: 'OIL_CHANGE', label: 'Oil Change' },
    { value: 'FILTER', label: 'Filter' },
    { value: 'BRAKES', label: 'Brakes' },
    { value: 'TYRES', label: 'Tyres' },
    { value: 'ELECTRICAL', label: 'Electrical' },
    { value: 'INSPECTION', label: 'Inspection' },
    { value: 'REPAIR', label: 'Repair' },
    { value: 'OTHER', label: 'Other' },
  ],
  PROPERTY: [
    { value: 'PLUMBING', label: 'Plumbing' },
    { value: 'ELECTRICAL', label: 'Electrical' },
    { value: 'HEATING_HVAC', label: 'Heating / HVAC' },
    { value: 'ROOF', label: 'Roof' },
    { value: 'PAINTING', label: 'Painting' },
    { value: 'PEST_CONTROL', label: 'Pest Control' },
    { value: 'APPLIANCE_REPAIR', label: 'Appliance Repair' },
    { value: 'CLEANING', label: 'Cleaning' },
    { value: 'INSPECTION', label: 'Inspection' },
    { value: 'RENOVATION', label: 'Renovation' },
    { value: 'OTHER', label: 'Other' },
  ],
  PLANT: [
    { value: 'WATERING', label: 'Watering' },
    { value: 'FERTILIZING', label: 'Fertilizing' },
    { value: 'REPOTTING', label: 'Repotting' },
    { value: 'PRUNING', label: 'Pruning' },
    { value: 'PEST_DISEASE_TREATMENT', label: 'Pest / Disease Treatment' },
    { value: 'SOIL_CHANGE', label: 'Soil Change' },
    { value: 'PROPAGATION', label: 'Propagation' },
    { value: 'OTHER', label: 'Other' },
  ],
  MACHINE: [
    { value: 'CLEANING', label: 'Cleaning' },
    { value: 'LUBRICATION', label: 'Lubrication' },
    { value: 'INSPECTION', label: 'Inspection' },
    { value: 'PART_REPLACEMENT', label: 'Part Replacement' },
    { value: 'CALIBRATION', label: 'Calibration' },
    { value: 'REPAIR', label: 'Repair' },
    { value: 'OTHER', label: 'Other' },
  ],
  TOOL: [
    { value: 'CLEANING', label: 'Cleaning' },
    { value: 'SHARPENING', label: 'Sharpening' },
    { value: 'BLADE_BIT_REPLACEMENT', label: 'Blade / Bit Replacement' },
    { value: 'BATTERY_SERVICE', label: 'Battery Service' },
    { value: 'INSPECTION', label: 'Inspection' },
    { value: 'REPAIR', label: 'Repair' },
    { value: 'OTHER', label: 'Other' },
  ],
  DEVICE: [
    { value: 'SOFTWARE_UPDATE', label: 'Software Update' },
    { value: 'CLEANING', label: 'Cleaning' },
    { value: 'BATTERY_SERVICE', label: 'Battery Service' },
    { value: 'PART_REPLACEMENT', label: 'Part Replacement' },
    { value: 'REPAIR', label: 'Repair' },
    { value: 'OTHER', label: 'Other' },
  ],
  PRINTER_3D: [
    { value: 'NOZZLE_CHANGE', label: 'Nozzle Change' },
    { value: 'BED_LEVELING', label: 'Bed Leveling' },
    { value: 'BELT_TENSIONING', label: 'Belt Tensioning' },
    { value: 'FIRMWARE_UPDATE', label: 'Firmware Update' },
    { value: 'CLEANING', label: 'Cleaning' },
    { value: 'CALIBRATION', label: 'Calibration' },
    { value: 'PART_REPLACEMENT', label: 'Part Replacement' },
    { value: 'REPAIR', label: 'Repair' },
    { value: 'OTHER', label: 'Other' },
  ],
  PET: [
    { value: 'VET_VISIT', label: 'Vet Visit' },
    { value: 'VACCINATION', label: 'Vaccination' },
    { value: 'GROOMING', label: 'Grooming' },
    { value: 'DENTAL_CARE', label: 'Dental Care' },
    { value: 'FLEA_TICK_TREATMENT', label: 'Flea / Tick Treatment' },
    { value: 'NAIL_TRIM', label: 'Nail Trim' },
    { value: 'MEDICATION', label: 'Medication' },
    { value: 'OTHER', label: 'Other' },
  ],
  AQUARIUM: [
    { value: 'WATER_CHANGE', label: 'Water Change' },
    { value: 'FERTILIZING', label: 'Fertilizing' },
    { value: 'FILTER_CLEANING', label: 'Filter Cleaning' },
    { value: 'WATER_TESTING', label: 'Water Testing' },
    { value: 'ALGAE_CLEANING', label: 'Algae Cleaning' },
    { value: 'NEW_PLANT_ADDED', label: 'New Plant Added' },
    { value: 'NEW_LIVESTOCK_ADDED', label: 'New Livestock Added' },
    { value: 'EQUIPMENT_CHECK', label: 'Equipment Check' },
    { value: 'CO2_REFILL', label: 'CO2 Refill' },
    { value: 'SUBSTRATE_CLEANING', label: 'Substrate Cleaning' },
    { value: 'OTHER', label: 'Other' },
  ],
  POOL: [
    { value: 'WATER_TESTING', label: 'Water Testing' },
    { value: 'CHEMICAL_BALANCING', label: 'Chemical Balancing' },
    { value: 'FILTER_CLEANING', label: 'Filter Cleaning' },
    { value: 'PUMP_MAINTENANCE', label: 'Pump Maintenance' },
    { value: 'CLEANING_VACUUMING', label: 'Cleaning / Vacuuming' },
    { value: 'COVER_MAINTENANCE', label: 'Cover Maintenance' },
    { value: 'WINTERIZING', label: 'Winterizing' },
    { value: 'OTHER', label: 'Other' },
  ],
  BOAT: [
    { value: 'ENGINE_SERVICE', label: 'Engine Service' },
    { value: 'OIL_CHANGE', label: 'Oil Change' },
    { value: 'HULL_CLEANING', label: 'Hull Cleaning' },
    { value: 'ANTIFOULING', label: 'Antifouling' },
    { value: 'ELECTRICAL', label: 'Electrical' },
    { value: 'SAFETY_EQUIPMENT_CHECK', label: 'Safety Equipment Check' },
    { value: 'WINTERIZING', label: 'Winterizing' },
    { value: 'REPAIR', label: 'Repair' },
    { value: 'OTHER', label: 'Other' },
  ],
  DRONE: [
    { value: 'FIRMWARE_UPDATE', label: 'Firmware Update' },
    { value: 'PROPELLER_REPLACEMENT', label: 'Propeller Replacement' },
    { value: 'BATTERY_CHECK', label: 'Battery Check' },
    { value: 'CALIBRATION', label: 'Calibration' },
    { value: 'MOTOR_SERVICE', label: 'Motor Service' },
    { value: 'REPAIR', label: 'Repair' },
    { value: 'OTHER', label: 'Other' },
  ],
  INSTRUMENT: [
    { value: 'STRING_CHANGE', label: 'String Change' },
    { value: 'TUNING', label: 'Tuning' },
    { value: 'CLEANING_POLISHING', label: 'Cleaning / Polishing' },
    { value: 'SETUP_ADJUSTMENT', label: 'Setup / Adjustment' },
    { value: 'REPAIR', label: 'Repair' },
    { value: 'OTHER', label: 'Other' },
  ],
  BICYCLE: [
    { value: 'CHAIN_LUBRICATION', label: 'Chain Lubrication' },
    { value: 'TYRE_CHANGE', label: 'Tyre Change' },
    { value: 'BRAKE_ADJUSTMENT', label: 'Brake Adjustment' },
    { value: 'GEAR_TUNING', label: 'Gear Tuning' },
    { value: 'WHEEL_TRUING', label: 'Wheel Truing' },
    { value: 'CLEANING', label: 'Cleaning' },
    { value: 'PART_REPLACEMENT', label: 'Part Replacement' },
    { value: 'REPAIR', label: 'Repair' },
    { value: 'OTHER', label: 'Other' },
  ],
  SOLAR: [
    { value: 'PANEL_CLEANING', label: 'Panel Cleaning' },
    { value: 'INVERTER_CHECK', label: 'Inverter Check' },
    { value: 'WIRING_INSPECTION', label: 'Wiring Inspection' },
    { value: 'PERFORMANCE_CHECK', label: 'Performance Check' },
    { value: 'REPAIR', label: 'Repair' },
    { value: 'OTHER', label: 'Other' },
  ],
  CUSTOM: [
    { value: 'CLEANING', label: 'Cleaning' },
    { value: 'INSPECTION', label: 'Inspection' },
    { value: 'REPAIR', label: 'Repair' },
    { value: 'REPLACEMENT', label: 'Replacement' },
    { value: 'OTHER', label: 'Other' },
  ],
}

export function getMaintenanceCategories(itemType: ItemType): MaintenanceCategoryDef[] {
  return MAINTENANCE_CATEGORIES[itemType]
}
